#!/bin/bash
#
# call.sh
# Copyright (C) 2018 jack <jack@HP-WorkStation>
#
# Distributed under terms of the MIT license.
#

#. ./fabric.conf
. ./k8.conf
docker exec cli $ID chaincode invoke -n $CC -c '{"Args":["'"$1"'",'"$2"']}' -C ${CH}
