#!/bin/bash
#
# call.sh
# Copyright (C) 2018 jack <jack@HP-WorkStation>
#
# Distributed under terms of the MIT license.
#

#. ./fabric.con
. ./k8.conf
docker exec $ID peer chaincode query -n $CC -c '{"Args":["'"$1"'",'"$2"']}' -C $CH
