#!/bin/bash
#
# call.sh
# Copyright (C) 2018 jack <jack@HP-WorkStation>
#
# Distributed under terms of the MIT license.
#

. ./fabric.conf

docker exec \
    -e "CORE_PEER_ADDRESS=peer$PEER.org$ORG.example.com:7051" \
    -e "CORE_PEER_LOCALMSPID=Org${ORG}MSP" \
    -e "CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org$ORG.example.com/users/Admin@org$ORG.example.com/msp" \
    cli peer chaincode query -n $1cc -c '{"Args":["'"$2"'",'"$3"']}' -C ${CHANNEL[$1]}
